config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  # resources :users
  resources :users do
    resources :microposts, only: [:create, :destroy]
    # post 'microposts', to: 'microposts#create'
    # delete 'microposts/:id', to: 'microposts#destroy'
  end
  resources :microposts do
    resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true, counter_cache: true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  has_many :likes, as: :likeable, dependent: :destroy
  belongs_to :user
  belongs_to :wall

  scope :sorted, -> { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :body, presence: true, length: { maximum: 140}
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveModel::Callbacks

  after_create do
    self.create_wall
  end

  has_many :microposts, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_one :wall, dependent: :destroy
  has_one_attached :avatar

  attr_accessor :remember_token

  validates :avatar, content_type: ['image/png', 'image/jpeg'],
            size: {less_than: 1.megabyte}
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, format: {with: URI::MailTo::EMAIL_REGEXP}, length: {maximum: 255}
  validates :password, presence: true, confirmation: true, length: {minimum: 6}, allow_nil: true
  validates :password_confirmation, presence: true, allow_blank: true

  before_save { self.email = email.downcase }

  has_secure_password

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/models/wall.rb
class Wall < ApplicationRecord
  has_many :microposts
  belongs_to :user

  validates :user_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  def logged_in_user
    unless logged_in?
      flash[:alert] = 'Войдите в аккаунт'
      render 'users/unauthorized_unforbidden', status: :unauthorized
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :logged_in_user, only: [:create]

  def create
    @micropost = Micropost.find(params[:micropost_id])

    @like = @micropost.likes.find_by(user_id: current_user.id)
    if @like.present?
      @like.destroy
    else

      @like = @micropost.likes.create(user_id: current_user.id)
    end

    render "create.js.erb"
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :find_user, only: [:create, :destroy]
  before_action :correct_user, only: [:destroy]

  def create
    @micropost = Micropost.create(body: microposts_params[:body],
                                  user_id: current_user.id,
                                  wall_id: @user.wall.id)

    redirect_to user_path(@user)
  end

  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.delete

    redirect_to user_path(@user)
  end

  private

  def microposts_params
    params.require(:microposts).permit(:body)
  end

  def find_user
    @user = User.find(params[:user_id])
  end

  def correct_user
    @user = User.find_by(id: params[:user_id])
    render file: "#{Rails.root}/public/403.html", status: :forbidden unless @user == current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)

    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      params[:session][:remember_me] == '1' ? remember(@user): forget(@user)

      redirect_to user_path(@user), notice: 'Вы вошли на сайт'
    else
      flash.now[:alert] = 'Неправильный email или пароль'

      render 'new'
    end
  end

  def destroy
    log_out if logged_in?

    redirect_to root_path, notice: 'Вы вышли из аккаунта'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :destroy]
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page], per_page: 15)
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user

      redirect_to user_path(@user), notice: 'Аккаунт создан'
    else
      render 'new'
    end
  end

  def show
    @microposts = @user.wall.microposts.sorted.paginate(page: params[:page], per_page: 15)
  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.save
      redirect_to user_path(@user), notice: 'Аккаунт изменен'
    else
      render 'edit'
    end
  end

  def destroy
    if current_user.admin?
      @user.destroy
      redirect_to users_path, notice: 'Аккаунт удален'
    else
      redirect_to users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end

  def find_user
    @user = User.find(params[:id])
  rescue
    render file: "#{Rails.root}/public/404.html", layout: false, status: 404
  end

  def correct_user
    @user = User.find_by(id: params[:id])
    render :'users/unauthorized_unforbidden', status: :forbidden unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, few, many)
    return many if (count % 100).between?(11, 14)

    case count % 10
    when 1 then "#{count} #{one}"
    when 2..4 then "#{count} #{few}"
    else
      "#{count} #{many}"
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
  def likes(micropost)
    "\u{202F}#{micropost.likes_count}" if micropost.likes_count.positive?
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
  def find_avatar_for_micropost(micropost)
    user = User.find(micropost.user_id)
    user.avatar
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= begin
      if session[:user_id]
        User.find_by(id: session[:user_id])
      elsif cookies.signed[:user_id]
        user = User.find_by(id: cookies.signed[:user_id])
        if user && user.authenticated?(cookies[:remember_token])
          log_in user
          user
        end
      end
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def logged_in?
    current_user.present?
  end

  def forget(user)
    user.forget
    cookies.delete([:user_id])
    cookies.delete([:remember_token])
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'SocialNetwork', root_path, class: 'navbar-brand' %>
    </div>

    <% if logged_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to users_path, class: 'button white' do %>
            <span class="glyphicon glyphicon-list-alt"></span>Пользователи
          <% end %>
        </li>

        <li><%= link_to user_path(current_user), class: 'button white' do %>
            <span class="glyphicon glyphicon-user"></span><%= current_user.email %>
          <% end %>
        </li>

        <li>
          <%= link_to logout_path, method: :delete, class: 'button white' do %>
            <span class="glyphicon glyphicon-log-out"></span>Выход
          <% end %>
        </li>
      </ul>
    <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to signup_path, class: 'button white' do %>
            <span class="glyphicon glyphicon-user"></span>Регистрация
          <% end %>
        </li>

        <li><%= link_to login_path, class: 'button white' do %>
            <span class="glyphicon glyphicon-log-in"></span>Вход
          <% end %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>
<br>

app/views/layouts/_user_form.html.erb
<%= form_with(url: login_path, scope: :session) do |form| %>

  <%= form.label :email, 'Почта' %>
  <p><%= form.email_field :email, class: 'form-control' %></p>

  <%= form.label :password, 'Пароль' %>
  <p><%= form.password_field :password, class: 'form-control' %></p>

  <p><%= form.label :remember_me, class: "checkbox inline" do %></p>
      <p>
        <%= form.check_box :remember_me %>
        <span>Запомнить меня</span>
      </p>
    <% end %>

    <p><%= form.submit "Войти", class: "btn btn-primary" %></p>
<% end %>
<br>
<p>Нет аккаунта? <%= link_to 'Зарегистрироваться', new_user_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialNetwork</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
  </body>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
</html>

app/views/likes/_like.html.erb
<%= content_tag "div", id: "like-#{micropost.id}" do %>
  <% if micropost.likes.find_by(user_id: current_user&.id).present? %>
    <%= link_to micropost_likes_path(micropost), method: :post, remote: true do %>
      <span class="glyphicon glyphicon-heart"><%= likes(micropost) %></span>
    <% end %>
  <% else %>
    <%= link_to micropost_likes_path(micropost), method: :post, remote: true do %>
      <span class="glyphicon glyphicon-heart-empty"><%= likes(micropost) %></span>
    <% end %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
document.getElementById("like-<%= @micropost.id %>").innerHTML = "<%= j render "likes/like", micropost: @micropost %>"

app/views/microposts/_form_micropost.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_with url: user_microposts_url(@user), scope: 'microposts', method: :post do |form| %>
      <%= form.label :body, 'Введите сообщение' %>
      <p><%= form.text_area :body, class: 'form-control' %></p>

      <p><%= form.submit 'Отправить на стену', class: "btn btn-warning" %></p>
    <% end %>
  </div>
</div>

app/views/microposts/_micropost.html.erb
<li>
    <span class="avatar">
      <% if find_avatar_for_micropost(micropost).attached? %>
        <%= image_tag find_avatar_for_micropost(micropost), class: 'img-circle', style: "height:50px;width:50px;"  %>
      <% else %>
        <%= image_tag ("photo-profile.jpg"), class: 'img-circle', style: "height:50px;width:50px;"  %>
      <% end %>
    </span>
    <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
    <span class="body"><%= micropost.body %></span>
    <span class="trash">
      <% if @user == current_user %>
        <%= link_to user_micropost_url(@user, micropost), method: :delete,
                  data: {confirm: "Вы уверены что хотите удалить сообщение?"} do %>
        <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      <% end %>
    </span>
  <span class="likes"><%= render 'likes/like', micropost: micropost %></span>
  <span class="timestamp">
      Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    </span>
</li>
  <%#= image_tag Current.user.avatar.variant(resize_to_limit: [100, 100]) %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger">
      Форма содержит <%= inclination(object.errors.count, 'ошибку', 'ошибки', 'ошибок') %>:
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    </div>
<% end %>

app/views/shared/_flashes.html.erb
<br>
<% if flash[:notice].present? %>
  <p class="alert alert-info"><%= flash[:notice] %></p>
<% elsif flash[:alert].present? %>
  <p class="alert alert-warning"><%= flash[:alert] %></p>
<% end %>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="jumbotron text-center">
      <h2>Добро пожаловать в SocialNetwork</h2>
     <br>

        <div class="container" style="width:570px; height:300px">
          <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
              <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
              <div class="item active">
                <%= image_tag("banner-1.jpg", style: "height:300px;width:100%;") %>
                <div class="carousel-caption">
                  <h1>Welcome</h1>
                </div>
              </div>

              <div class="item">
                <%= image_tag("banner-2.jpg", style: "height:300px;width:100%;") %>
              </div>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>

            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
    </div>
  </div>

  <div class=" jumbotron col-md-6">
    <h2 class='text-center'>Вход</h2>
      <%= render 'layouts/user_form' %>
  </div>

</div>

app/views/users/edit.html.erb
<h1 class="text-center">Редактирование</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @user do |form| %>
      <%= render 'shared/error_messages', object: form.object %>

      <p><%= form.label :name, 'Ваше имя' %></p>
      <p><%= form.text_field :name, class: 'form-control' %></p>

      <p><%= form.label :email, 'Почта' %></p>
      <p><%= form.text_field :email, class: 'form-control' %></p>

      <p><%= form.label :password, 'Пароль' %></p>
      <p><%= form.password_field :password, class: 'form-control' %></p>

      <p><%= form.label :password_confirmation, 'Повторите пароль' %></p>
      <p><%= form.password_field :password_confirmation, class: 'form-control' %></p>

      <p><%= form.label :avatar, 'Загрузка нового фото для изменения' %></p>
      <p><%= form.file_field :avatar %></p>

      <p><%= form.submit 'Редактировать', class: "btn btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1 class="text-center">Все пользователи</h1>

<%= will_paginate %>

  <% @users.each do |user| %>
    <div class="row well well-md">
      <div class="col-md-2">
        <% if user.avatar.attached? %>
          <%= image_tag user.avatar, class: 'img-circle', style: 'width: 100px;'  %>
        <% else %>
          <%= image_tag ("photo-profile.jpg"), class: 'img-circle', style: 'width: 100px;'  %>
        <% end %>
      </div>
      <div class="col-md-4">
        <h4><%= link_to user.name, user %></h4>
        <p><%= user.email %></p>
        <% if current_user.admin? %>
          <%= link_to user_path(user), method: :delete, class: 'button white',
                      data: {confirm: "Вы уверены что хотите удалить пользователя?"} do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>

<%= will_paginate %>

app/views/users/new.html.erb
<h1 class="text-center">Регистрация</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @user do |form| %>
      <%= render 'shared/error_messages', object: form.object %>

      <%= form.label :name, 'Ваше имя' %>
      <p><%= form.text_field :name, class: 'form-control' %></p>

      <%= form.label :email, 'Почта' %>
      <p><%= form.text_field :email, class: 'form-control' %></p>

      <%= form.label :password, 'Пароль' %>
      <p><%= form.password_field :password, class: 'form-control' %></p>

      <%= form.label :password_confirmation, 'Повторите пароль' %>
      <p><%= form.password_field :password_confirmation, class: 'form-control' %></p>

      <%= form.label :avatar, 'Загрузка фото' %>
      <p><%= form.file_field :avatar %></p>

      <p><%= form.submit 'Зарегистрироваться', class: "btn btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="well well-md">
      <div class="row">
        <div class="col-md-6 col-md-4 text-center">
          <% if @user.avatar.attached? %>
            <%= image_tag @user.avatar, class: 'img-thumbnail'  %>
          <% else %>
            <%= image_tag ("photo-profile.jpg"), class: 'img-thumbnail'  %>
          <% end %>
          <br><br>
          <div>
            <% if @user == current_user %>
              <%= button_to 'Редактировать', edit_user_path(@user), method: :get, class: 'btn btn-info' %>
            <% end %>
            <br />
          </div>
        </div>
        <div class="col-sm-6 col-md-8">
          <h3><%= @user.name %></h3>
          <small><cite>Город, страна<i class="glyphicon glyphicon-map-marker">
          </i></cite></small>
          <p>
            <i class="glyphicon glyphicon-envelope"></i><%= @user.email %>
            <br />
            <i class="glyphicon glyphicon-registration-mark"></i><%= @user.created_at.strftime("Зарегистрирован: %d.%m.%Y") %>
          </p>
<!--            <button type="button" class="btn btn-primary">-->
<!--              #-->
<!--            </button>-->
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-8 col-md-offset-2">
    <% if logged_in? %>
      <%= render 'microposts/form_micropost' %>
    <% end %>
    <h2>Стена (<%= inclination(@microposts.count, 'запись', 'записи', 'записей')%>)</h2>
    <% if @microposts.any? %>
        <ol class="microposts">
          <%= render @microposts %>
        </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/unauthorized_unforbidden.html.erb
<script type="text/javascript">
    window.location.replace("<%= root_path %>");
</script>